Vagrant.configure(2) do |config|
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.box = "chyld/venus"
  config.vm.hostname = "hydrogen"
  config.vm.provider "virtualbox" do |v|
    v.name = "hydrogen"
    v.memory = 1024
    v.cpus = 2
  end
end
